# 应用名称
spring:
  application:
    name: couldPayment
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库驱动：
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/mycloud?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: yyqdemao
# 应用服务 WEB 访问端口
server:
  port: 8002
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.yyqdemao.devment.could_payment8001.mybatis.entity
eureka:
  instance:
    #服务id
    instance-id: payment8002
    #显示ip
    prefer-ip-address: true
    # eureka 客户端向服务端发送心跳间隔 默认30s
    lease-renewal-interval-in-seconds: 1
    #eureka 服务端在收到最候一次心跳等待上限 默认90s 超时剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
