# 应用名称
spring:
  application:
    name: could_payment8001
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库驱动：
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: yyqdemao
# 应用服务 WEB 访问端口
server:
  port: 8001
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
#指定Mybatis的实体目录
  type-aliases-package: com.yyqdemao.devment.could_payment8001.mybatis.entity


